/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamsIndexRouteImport } from './routes/exams/index'
import { Route as ExamsCategoryExamYearRouteImport } from './routes/exams/$category/$exam/$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsIndexRoute = ExamsIndexRouteImport.update({
  id: '/exams/',
  path: '/exams/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsCategoryExamYearRoute = ExamsCategoryExamYearRouteImport.update({
  id: '/exams/$category/$exam/$year',
  path: '/exams/$category/$exam/$year',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/exams/$category/$exam/$year': typeof ExamsCategoryExamYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exams': typeof ExamsIndexRoute
  '/exams/$category/$exam/$year': typeof ExamsCategoryExamYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exams/': typeof ExamsIndexRoute
  '/exams/$category/$exam/$year': typeof ExamsCategoryExamYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exams/' | '/exams/$category/$exam/$year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exams' | '/exams/$category/$exam/$year'
  id: '__root__' | '/' | '/exams/' | '/exams/$category/$exam/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamsIndexRoute: typeof ExamsIndexRoute
  ExamsCategoryExamYearRoute: typeof ExamsCategoryExamYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/': {
      id: '/exams/'
      path: '/exams'
      fullPath: '/exams/'
      preLoaderRoute: typeof ExamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams/$category/$exam/$year': {
      id: '/exams/$category/$exam/$year'
      path: '/exams/$category/$exam/$year'
      fullPath: '/exams/$category/$exam/$year'
      preLoaderRoute: typeof ExamsCategoryExamYearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamsIndexRoute: ExamsIndexRoute,
  ExamsCategoryExamYearRoute: ExamsCategoryExamYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
