/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamIndexRouteImport } from './routes/exam/index'
import { Route as ExamExamNameRouteImport } from './routes/exam/$examName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamIndexRoute = ExamIndexRouteImport.update({
  id: '/exam/',
  path: '/exam/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamExamNameRoute = ExamExamNameRouteImport.update({
  id: '/exam/$examName',
  path: '/exam/$examName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam/$examName': typeof ExamExamNameRoute
  '/exam/': typeof ExamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam/$examName': typeof ExamExamNameRoute
  '/exam': typeof ExamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam/$examName': typeof ExamExamNameRoute
  '/exam/': typeof ExamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/exam/$examName' | '/exam/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/exam/$examName' | '/exam'
  id: '__root__' | '/' | '/exam/$examName' | '/exam/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamExamNameRoute: typeof ExamExamNameRoute
  ExamIndexRoute: typeof ExamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/': {
      id: '/exam/'
      path: '/exam'
      fullPath: '/exam/'
      preLoaderRoute: typeof ExamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$examName': {
      id: '/exam/$examName'
      path: '/exam/$examName'
      fullPath: '/exam/$examName'
      preLoaderRoute: typeof ExamExamNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamExamNameRoute: ExamExamNameRoute,
  ExamIndexRoute: ExamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
